// Generated by `npx convex dev`; suppress the editor diagnostic until generation runs.
// @ts-ignore TS2307: Convex creates this module during project generation.
import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

/**
 * Create a consultation request.
 *
 * This creates the consultation record.
 * A CRM lead can also be created from the same request
 * after we confirm the exact structure of your existing
 * leads table.
 */
export const createConsultation = mutation({
  args: {
    name: v.string(),
    phone: v.string(),
    email: v.optional(v.string()),
    service: v.string(),
    message: v.optional(v.string()),
    preferredDate: v.optional(v.string()),
    preferredTime: v.optional(v.string()),
  },

  handler: async (ctx, args) => {
    const now = Date.now();

    const consultationId = await ctx.db.insert("consultations", {
      name: args.name,
      phone: args.phone,
      email: args.email,
      service: args.service,
      message: args.message,
      createdAt: now,
      status: "NEW",
    });

    return consultationId;
  },
});


/**
 * Get recent consultation requests.
 *
 * Useful later for the admin dashboard.
 */
export const listConsultations = query({
  args: {},

  handler: async (ctx) => {
    return await ctx.db
      .query("consultations")
      .order("desc")
      .take(100);
  },
});