import Link from 'next/link';
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Check, Home as HomeIcon, MessageCircle, Play, ShieldCheck, Sparkles, Star, Users } from 'lucide-react';
import { astrologyCourses, astrologyTeachers, testimonials } from '@/lib/data';

const services = [
  { title: 'Birth Chart Reading', text: 'Understand the main themes in your birth chart and ask the questions that matter to you.', icon: Star },
  { title: 'Career & Direction', text: 'Use astrology as one way to think about work, change, timing and your next step.', icon: Sparkles },
  { title: 'Marriage & Relationships', text: 'Discuss relationship questions with a private and respectful approach.', icon: Users },
  { title: 'Vastu Guidance', text: 'Get simple suggestions for your home or workspace based on the space you live in.', icon: HomeIcon },
];

export default function Astrology() {
  return <main>
    <section className="astro-page-hero">
      <div className="container astro-hero-grid">
        <div><div className="eyebrow"><Star size={14} /> Divyajyoti Astrology</div><h1 className="display">Astrology you can understand. Guidance you can use.</h1><p>Learn astrology from the basics or speak to an experienced teacher about your personal questions. We keep the language clear, the process private and the learning practical.</p><div className="actions"><Link className="btn btn-gold" href="/consultation">Book a consultation <ArrowUpRight size={15}/></Link><Link className="btn btn-light" href="#classes">See classes <ArrowRight size={15}/></Link></div><div className="astro-hero-stats"><span><b>Live</b><small>teacher-led classes</small></span><span><b>Simple</b><small>step-by-step lessons</small></span><span><b>Personal</b><small>consultation support</small></span></div></div>
        <div className="astro-hero-visual"><div className="astro-hero-photo"/><div className="astro-paper"><div className="paper-heading">BIRTH CHART <span>DIVYAJYOTI</span></div><div className="paper-grid"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><small>Example learning chart</small></div></div>
      </div>
    </section>

    <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">What you can do here</div><h2 className="display">Choose the kind of help you need.</h2></div><p>There is no need to know astrology before you start. We explain the process before we begin.</p></div><div className="service-large-grid">{services.map(s => { const Icon=s.icon; return <div className="service-large" key={s.title}><div className="service-large-icon"><Icon/></div><h3>{s.title}</h3><p>{s.text}</p><Link href="/consultation">Learn more <ArrowUpRight size={14}/></Link></div> })}</div></div></section>

    <section className="section astro-learning" id="classes"><div className="container"><div className="section-head light-head"><div><div className="eyebrow gold-eyebrow">Astrology classes</div><h2 className="display">Start where you are.</h2></div><p>From the first lesson to practical chart reading, choose a course that matches your level.</p></div><div className="astro-course-list">{astrologyCourses.map((c, i)=><article className="astro-course-row" key={c.slug}><div className="astro-course-number">0{i+1}</div><div className="astro-course-cover" style={{backgroundImage:`url(${c.image})`}}><span>{c.level}</span><button aria-label="Preview course"><Play size={13} fill="currentColor"/></button></div><div className="astro-course-copy"><div className="eyebrow gold-eyebrow">{c.category}</div><h3>{c.title}</h3><p>{c.description}</p><div className="astro-course-meta"><span><CalendarDays size={14}/> {c.duration}</span><span><BookOpen size={14}/> {c.format}</span><span>{c.mode}</span></div></div><Link className="btn btn-white btn-sm" href="/contact">Ask about this class <ArrowUpRight size={13}/></Link></article>)}</div></div></section>

    <section className="section" id="teachers"><div className="container"><div className="teacher-heading"><div><div className="eyebrow">Our teachers</div><h2 className="display">Experienced people. Clear teaching.</h2></div><p>Teacher information can be updated with your real faculty profiles before launch. The structure is ready for experience, qualifications, specialties and student feedback.</p></div><div className="teacher-grid">{astrologyTeachers.map(t=><article className="teacher-card" key={t.name}><div className="teacher-photo" style={{backgroundImage:`url(${t.image})`}}><span>{t.role}</span></div><div className="teacher-body"><h3>{t.name}</h3><p>{t.bio}</p><div className="teacher-tags">{t.specialties.map(s=><span key={s}>{s}</span>)}</div><div className="teacher-experience"><Star size={14} fill="currentColor"/> {t.experience}</div></div></article>)}</div></div></section>

    <section className="section astro-process"><div className="container process-grid"><div><div className="eyebrow">How a consultation works</div><h2 className="display">Three simple steps.</h2><p className="copy">You do not need to prepare a long list. Just tell us what you want to understand and we will guide the conversation.</p></div><div className="process-list"><div><b>01</b><span><strong>Choose a session</strong><small>Select the type of consultation that fits your question.</small></span></div><div><b>02</b><span><strong>Share your details</strong><small>We collect only the information needed for the session.</small></span></div><div><b>03</b><span><strong>Have the conversation</strong><small>Ask questions, understand the reading and decide what is useful to you.</small></span></div></div></div></section>

    <section className="section" id="feedback"><div className="container"><div className="section-head"><div><div className="eyebrow">Feedback</div><h2 className="display">Simple words from learners and clients.</h2></div></div><div className="testimonial-grid">{testimonials.map(t=><article className="testimonial" key={t.name}><div className="quote-mark">“</div><p>{t.text}</p><div className="testimonial-person"><div className="person-avatar">{t.name[0]}</div><div><b>{t.name}</b><small>{t.role}</small></div></div></article>)}</div></div></section>

    <section className="section" id="vastu"><div className="container vastu-card"><div className="vastu-visual"/><div className="vastu-copy"><div className="eyebrow">Vastu guidance</div><h2 className="display">Practical suggestions for your space.</h2><p>We look at the layout, direction and use of your home or workspace and explain suggestions in simple language.</p><div className="intro-points"><span><Check/> Home & office</span><span><Check/> Floor plan review</span><span><Check/> Simple changes</span><span><Check/> Clear explanation</span></div><Link className="btn btn-dark" href="/consultation">Ask about Vastu <ArrowUpRight size={15}/></Link></div></div></section>

    <section className="section final-cta"><div className="container final-cta-inner"><div className="eyebrow">Ready when you are</div><h2 className="display">Start learning or book a private session.</h2><p>Tell us what you need and we will help you choose the right place to begin.</p><div className="actions"><Link className="btn btn-gold" href="#classes">Explore classes <ArrowRight size={15}/></Link><Link className="btn btn-white" href="/consultation">Book consultation <ArrowUpRight size={15}/></Link></div></div></section>
  </main>
}
